version: '3.7'

volumes:
    mysql-data:
        driver: local

services:
    web:
        image: bref/fpm-dev-gateway
        ports:
        - 8000:80
        volumes:
        - .:/var/task
        depends_on:
        - php
        - db
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public

    php:
        image: bref/php-73-fpm-dev
        volumes:
        - .:/var/task

    db:
        image: mysql:5.7
        ports:
        - 3306:3306
        volumes:
        - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: kdti
            MYSQL_ROOT_PASSWORD: root

    dev:
        image: ambientum/php:7.3-nginx
        container_name: app
        volumes:
            - .:/var/www/app
        ports:
            - "8090:8080"
        environment:
            XDEBUG_ENABLED: 'true'
        depends_on:
            - db

    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: server-id
            BLACKFIRE_SERVER_TOKEN: server-token
